## Assignment Numpy Basic

Consider the below code to answer further questions:

`import numpy as np`

`list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]`

`array_list = np.array(object = list_)`

In [18]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In Python, list may contain the items with different data types, whereas in array holds data of the same data type.
In array, insertion and deletion is costly compared to list, as it holds data linearly. However Arrays are faster compared to lists.

An array is faster than a list in python since all the elements stored in an array are homogeneous i.e., they have the same data type whereas a list contains heterogeneous elements.

Lists are not optimised like arrays, hence it is easy to retrieve the data from the array.

In [19]:
# List example:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print(type(lst))
for i in lst:
    print(i)

<class 'list'>
1
2
3
['4', '5']


In [20]:
for i in array_list:
    print(i)

1
2
3
4
5


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [21]:
for i in lst:
    print(f"data type of {i} is {type(i)}")

data type of 1 is <class 'str'>
data type of 2 is <class 'str'>
data type of 3 is <class 'str'>
data type of ['4', '5'] is <class 'list'>


In [22]:
for i in array_list:
    print(f"data type of {i} is {type(i)}")

data type of 1 is <class 'numpy.str_'>
data type of 2 is <class 'numpy.str_'>
data type of 3 is <class 'numpy.str_'>
data type of 4 is <class 'numpy.str_'>
data type of 5 is <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
`array_list = np.array(object = list_, dtype = int)`

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

Answer:
Yes there is difference between `num_list` and `num_array`. As `num_list` holds items of type `list` where as `num_array` holds items of type `ndarray` which means it is a multi-dimentional array.

In [31]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

for i in num_list:
    print(type(i))

<class 'list'>
<class 'list'>


In [32]:
for i in num_array:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Q4. Write a code to find the following characteristics of variable, num_array:
##### (i) shape
##### (ii) size

In [35]:
num_array.shape

(2, 3)

In [36]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.random.randint(0,1, (3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [44]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])